config/routes.rb
Bag::Application.routes.draw do
  root 'categories#index'

  get '/admin/products/new', to: 'products#new'
  post '/admin/products/select', to: 'products#select'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

 resources :categories do
  resources :subcategories do
  resources :products
 end
end

resources :subcategories 
resources :products
resources :sessions
resources :users
resources :coms
resources :carts
resources :items
resources :orders

match 'sessions_destroy',    to: 'sessions#destroy',    via: :all

end

app/models/admin_user.rb
# -*- coding: utf-8 -*-
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
# -*- coding: utf-8 -*-
class Cart < ActiveRecord::Base
	has_many :items
end

app/models/category.rb
# -*- coding: utf-8 -*-
class Category < ActiveRecord::Base
	
	has_many :products
	has_many :subcategories

mount_uploader :picture, PictureUploader

end

app/models/color.rb
# -*- coding: utf-8 -*-
class Color < ActiveRecord::Base

	has_one :product

end

app/models/com.rb
# -*- coding: utf-8 -*-
class Com < ActiveRecord::Base
validates_presence_of :body, message: "не должен быть пустой"

	validates :body, :length => {:maximum => 500}, :format => {with: /[a-zA-Z0-9а-я.,А-Я-?()!_]/ , message: "пишите текст и цифры"}

	belongs_to :product
	belongs_to :user
end

app/models/item.rb
# -*- coding: utf-8 -*-
class Item < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	belongs_to :order
end

app/models/order.rb
# -*- coding: utf-8 -*-
class Order < ActiveRecord::Base
has_many :items, dependent: :destroy

validates :user_name, :adress, presence: true 
validates :email, :format => {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "неверный формат" }
end

app/models/product.rb
# -*- coding: utf-8 -*-
class Product < ActiveRecord::Base

	belongs_to :category
	belongs_to :subcategory

	mount_uploader :picture, PictureUploader
	mount_uploader :picture1, PictureUploader
	mount_uploader :picture2, PictureUploader

	belongs_to :color
	has_many :com
	#validates_presence_of :name, :subcategory_id, :category_id, 

end

app/models/subcategory.rb
# -*- coding: utf-8 -*-
class Subcategory < ActiveRecord::Base
	belongs_to :category
	has_many :products




end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
has_secure_password 


	validates_presence_of :name, :email, message: "не должен быть пустой"
	validates :email, :format => {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "не верный формат" }, :uniqueness => true
	
validates :name, :uniqueness => true, :format => {with: /[a-zA-ZА-Яa-я_1-90]/ , message: "недоступное" }

  validates_length_of :password, :within => 5..30,
    too_long: "слишком длинный",
    too_short: "должен состоять из 5 символов и более"

    has_many :com 

end

app/controllers/carts_controller.rb
# -*- coding: utf-8 -*-
class CartsController < ApplicationController

	def index
    @total_price = 0
    current_cart.items.each { |item| @total_price += item.quantity*item.price }
  end
   def destroy
    current_cart.destroy
    cart = Cart.create
    session[:cart_id] = cart.id
    redirect_to root_path
   end
   
end

app/controllers/coms_controller.rb
# -*- coding: utf-8 -*-
class ComsController < ApplicationController

def create 

	@comments = Com.new(params.require(:com).permit(:user_id, :body, :name_user, :product_id))

		if @comments.save
        redirect_to :back
    	else
        redirect_to :back , notice: 'ошибка, пустые поля, превышен максимум, или запрещен. символы'
		end

end

def destroy

if current_user and params[:name]==current_user.name
       Com.find(params[:id]).destroy
       #http://localhost:3000/products/114
else

end
redirect_to product_path(params[:id_product])

end

end

app/controllers/items_controller.rb
# -*- coding: utf-8 -*-
class ItemsController < ApplicationController
	def create
	
	if current_cart.items.where(product_id: params[:product_id]).any?
      item = current_cart.items.where(product_id: params[:product_id]).first
      item.quantity += 1
    else
      item = Item.new
      item.cart = current_cart
      product = Product.find(params[:product_id])
      item.product = product
      item.quantity = 1
      item.price = product.price
    end

    if item.save
      redirect_to :back, notice: 'Product added'
    else
      redirect_to :back, alert: 'Error'
    end

	end

  def destroy
    Item.find(params[:id]).destroy
    if Item.find_by(cart_id: current_cart.id)
    redirect_to :back
    else
    redirect_to root_url
    end
    #render json: Item.find_by(current_cart.id)

    #cart.find_by(params[:id])
    #redirect_to :back


  end


end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
	layout "some"

	def new
		@sign_in_view=false
		@user = User.new
	end

  	def create
		@user = User.new(params.require(:user).permit(:name, :password, :email, :password_confirmation))
		@user.email = params[:user][:email].downcase

		if @user.save
    		session[:user_id] = @user.id
        	redirect_to categories_path
		else
        	render action: "new" 
		end
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/coms_helper.rb
module ComsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/carts/index.html.erb
<center><h3><span class='text_span'>Корзина</span></h3></center>
<table class="cart_table">
<% current_cart.items.each_with_index do |item, i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= item.product.name %></td>
        <td><%= item.quantity %></td>
        <td><%=item.price*item.quantity %></td>
        <td><%= link_to 'удалить', item_path(item), method: :delete , class: 'text_span' %></td>
      </tr>
<% end %>
  <tr>
  <td colspan="5"><br><br><br><hr></td>
  </tr>
  <tr>
    <td colspan="3"><b>Итого</b></td>
    <td colspan="2"><b><%= @total_price %> грн.</b></td>
</tr>
<tr>
<td colspan="5" align='right'><br><br><br>
<%= link_to 'Очистить корзину',{controller: "carts", action: "destroy",id: current_cart.id },:method => :delete, class: 'button' %>
&emsp;&emsp;
<% if current_cart.items.any? %>
<%= link_to 'Оформить заказ', new_order_path, class: 'button' %>
<% end %>
</td>
</tr>
</table>

app/views/users/_user_sign_in_up.html.erb
<div class='sign_in'>
<%= link_to "Регистрация", new_user_path, class: 'reg_a' %><br>

<% if session[:user_id] %>
Неllo, <%= current_user.name %>
<%= link_to "Выход", :sessions_destroy, class: 'button' %>

<% else %>

<%= form_tag(controller: "sessions", action: "create") do  %>
<%= label_tag "Email" %>&emsp;
<%= text_field_tag 'email', nil, class: 'sing_email' %>
</br>
<%= label_tag "Пароль" %>
<%= password_field_tag 'password', nil, class: 'sing_email' %>
<%= submit_tag "Войти", class: 'button' %>
<% end %>



<% if flash[:error]==true %>
<span class='error'> неправильный пароль или email </span>
<% end %>

<% end %>
</div>

app/views/users/new.html.erb
<!------------------------>

<center>

<span class='text_span'> Регистрация </span>
<br><br>
<%= form_for @user, url: {action: "create", remote: true } do |f| %>
<table style='border:1px solid white;padding:30px;'>
<tr>
<td> 
    <%= f.label :name, "Имя" %>
</td>
<td>
    <%= f.text_field :name, class: 'dd' %>
</td>
</tr>
<tr>
<td> 
    <%= f.label :email, "Email" %>
</td>
<td>
    <%= f.text_field :email, class: 'dd' %>
</td>
</tr>
<tr>
<td> 
    <%= f.label :password, "Пароль" %>
</td>
<td>
    <%= f.password_field :password, class: 'dd' %>
</td>
</tr>
<tr>
<td> 
    <%= f.label :password_confirmation, "Еще раз пароль" %>&emsp;&emsp;
</td>
<td>
    <%= f.password_field :password_confirmation, class: 'dd' %>
</td>
</tr>
<tr>
<td colspan="2"> 
<br>
  <%= f.submit "Зарегистрироваться", class: 'button' %>
</td>
</tr>
<tr>
<td colspan="2" align="left" style="color:red">
<% if @user.errors.messages[:name].length!=0  %>
не правильное или занятое имя пользователя
</br>
<% end %>


<% if @user.errors.messages[:password].length!=0  %>
пароль или подтверждение не верные
</br>
возможно длинна пароля меньше 6 символов
</br>
<% end %>

<% if @user.errors.messages[:email].length!=0  %>
email существует, либо имеет не верный формат
<% end %>

</td>
</tr>
</table>
<% end %>

</br>
</center>