config/routes.rb
Bag::Application.routes.draw do
  root 'categories#index'

  get '/admin/products/new', to: 'products#new'
  post '/admin/products/select', to: 'products#select'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

 resources :categories do
  resources :subcategories do
  resources :products
 end
end

resources :subcategories 
resources :products
resources :sessions
resources :users
resources :coms
resources :carts
resources :items
resources :orders

match 'sessions_destroy',    to: 'sessions#destroy',    via: :all

end

app/models/admin_user.rb
# -*- coding: utf-8 -*-
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
# -*- coding: utf-8 -*-
class Cart < ActiveRecord::Base
	has_many :items
end

app/models/category.rb
# -*- coding: utf-8 -*-
class Category < ActiveRecord::Base
	
	has_many :products
	has_many :subcategories

mount_uploader :picture, PictureUploader

end

app/models/color.rb
# -*- coding: utf-8 -*-
class Color < ActiveRecord::Base

	has_one :product

end

app/models/com.rb
# -*- coding: utf-8 -*-
class Com < ActiveRecord::Base
validates_presence_of :body, message: "не должен быть пустой"

	validates :body, :length => {:maximum => 500}, :format => {with: /[a-zA-Z0-9а-я.,А-Я-?()!_]/ , message: "пишите текст и цифры"}

	belongs_to :product
	belongs_to :user
end

app/models/item.rb
# -*- coding: utf-8 -*-
class Item < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	belongs_to :order
end

app/models/order.rb
# -*- coding: utf-8 -*-
class Order < ActiveRecord::Base
has_many :items, dependent: :destroy

validates :user_name, :adress, presence: true 
validates :email, :format => {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "неверный формат" }
end

app/models/product.rb
# -*- coding: utf-8 -*-
class Product < ActiveRecord::Base

	belongs_to :category
	belongs_to :subcategory

	mount_uploader :picture, PictureUploader
	mount_uploader :picture1, PictureUploader
	mount_uploader :picture2, PictureUploader

	belongs_to :color
	has_many :com
	#validates_presence_of :name, :subcategory_id, :category_id, 

end

app/models/subcategory.rb
# -*- coding: utf-8 -*-
class Subcategory < ActiveRecord::Base
	belongs_to :category
	has_many :products




end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
has_secure_password 


	validates_presence_of :name, :email, message: "не должен быть пустой"
	validates :email, :format => {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "не верный формат" }, :uniqueness => true
	
validates :name, :uniqueness => true, :format => {with: /[a-zA-ZА-Яa-я_1-90]/ , message: "недоступное" }

  validates_length_of :password, :within => 5..30,
    too_long: "слишком длинный",
    too_short: "должен состоять из 5 символов и более"

    has_many :com 

end

app/controllers/coms_controller.rb
# -*- coding: utf-8 -*-
class ComsController < ApplicationController

def create 

	@comments = Com.new(params.require(:com).permit(:user_id, :body, :name_user, :product_id))

		if @comments.save
        redirect_to :back
    	else
        redirect_to :back , notice: 'ошибка, пустые поля, превышен максимум, или запрещен. символы'
		end

end

def destroy

if current_user and params[:name]==current_user.name
       Com.find(params[:id]).destroy
       #http://localhost:3000/products/114
else

end
redirect_to product_path(params[:id_product])

end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/coms_helper.rb
module ComsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_total_layouts.html.erb
<body>

<div class='body'>
<div class='header'>
<div class='logo'>YOUR NEW BAG</div>
<div class='on_root'> <%= link_to 'на главную', root_path %>&emsp;&emsp;
<%= link_to 'o нас', root_path %>&emsp;&emsp;

<% if current_cart.items.count>0 %>
<%= link_to(carts_path) do %>
В корзине: <%= current_cart.items.count %>
            <%= Russian.p(current_cart.items.count, "товар", "товара", "товаров") %>
<% end %>
<% end %>

</div>
</div>
<%= yield %>
<%= render partial: "users/user_sign_in_up" %>
</br></br></br></br>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bag</title>


  <%= stylesheet_link_tag    "application", "css","main", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<%= javascript_include_tag "jquery.ui-slider.js" %>
<%= javascript_include_tag "jquery.main.js" %>

</head>
<%= render 'layouts/total_layouts' %>
</html>

app/views/layouts/empty.html.erb
<%= yield %>

app/views/layouts/some.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bag</title>
  <%= stylesheet_link_tag    "application","product_show", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<%= javascript_include_tag "mootools.js" %>
<%= javascript_include_tag "moocicle.js" %>

</head>
<%= render 'layouts/total_layouts' %>
</html>